// src/components/Header.tsx
"use client";
import { Grid } from "@mui/material";
import Search from "./Search";
import Login from "./Login";
import Image from "next/image";

const Header = () => {

  return (
    <Grid
      container
      height={60}>
      <Grid
        item
        xs={6}
        sx={{ display: "flex", alignItems: "center" }}>
        <Image src="/vercel.svg" alt="Vercel Logo" width={100} height={24} priority />
      </Grid>
      <Grid
        item
        xs={6}
        sx={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <Search />
        <Login />
      </Grid>
    </Grid>
  );
};

export default Header;

// src/components/Header.vue
<template>
  <div class="header">
    <div class="header">
      <img alt="Vue" src="../assets/logo.png">
      <span>{{name}}</span>
    </div>
    <div class="header">
      <input type="text">
      <button>{{search}}</button>
    </div>
  </div>
</template>

<script>
export default {
  name: 'HeaderName',
  data() {
    return {
      name: 'MUI CORE',
      search: '登录',
    }
  },
}
</script>

<style scoped>
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
img{
  width: 20px;
  height: 20px;
  margin-right: 5px;
}
input{
  margin-right: 5px;
}
</style>
